repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Use the latest stable version of ruff
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        args: ["--check"]

