"""first migration

Revision ID: 8311ce351b45
Revises:
Create Date: 2025-09-04 22:48:44.780904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8311ce351b45"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("lemma", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column(
            "pos",
            sa.Enum(
                "NOUN",
                "VERB",
                "ADJECTIVE",
                "ADVERB",
                "PRONOUN",
                "PREPOSITION",
                "CONJUNCTION",
                "INTERJECTION",
                "ARTICLE",
                "DETERMINER",
                "PARTICLE",
                "OTHER",
                name="partofspeech",
            ),
            nullable=False,
        ),
        sa.Column("pos_specific", sa.String(), nullable=True),
        sa.Column("defs", sa.JSON(), nullable=False),
        sa.Column("synonyms", sa.JSON(), nullable=True),
        sa.Column("examples", sa.JSON(), nullable=True),
        sa.Column("freq_rank", sa.Integer(), nullable=True),
        sa.Column(
            "cefr",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefrlevel"),
            nullable=True,
        ),
        sa.Column(
            "gender",
            sa.Enum("MASCULINE", "FEMININE", "NEUTER", name="gender"),
            nullable=True,
        ),
        sa.Column("plural", sa.String(), nullable=True),
        sa.Column("audio", sa.Text(), nullable=True),
        sa.Column("src", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_word_id"), "word", ["id"], unique=False)
    op.create_index(op.f("ix_word_lang"), "word", ["lang"], unique=False)
    op.create_index(op.f("ix_word_lemma"), "word", ["lemma"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_word_lemma"), table_name="word")
    op.drop_index(op.f("ix_word_lang"), table_name="word")
    op.drop_index(op.f("ix_word_id"), table_name="word")
    op.drop_table("word")
    # ### end Alembic commands ###
